//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOTTab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KOTTabModalContainer : DbContext
    {
        public KOTTabModalContainer()
            : base("name=KOTTabModalContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<VacantTables_Result> VacantTables()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<VacantTables_Result>("VacantTables");
        }
    
        public virtual ObjectResult<OccupiedTableList_Result> OccupiedTableList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OccupiedTableList_Result>("OccupiedTableList");
        }
    
        public virtual ObjectResult<PaymentTableList_Result> PaymentTableList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaymentTableList_Result>("PaymentTableList");
        }
    
        public virtual ObjectResult<WaiterList_Result> WaiterList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WaiterList_Result>("WaiterList");
        }
    
        public virtual int UpdateTableStatus(Nullable<int> tableId, string tableStatus)
        {
            var tableIdParameter = tableId.HasValue ?
                new ObjectParameter("TableId", tableId) :
                new ObjectParameter("TableId", typeof(int));
    
            var tableStatusParameter = tableStatus != null ?
                new ObjectParameter("TableStatus", tableStatus) :
                new ObjectParameter("TableStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateTableStatus", tableIdParameter, tableStatusParameter);
        }
    
        public virtual ObjectResult<GetAllItems1_Result> GetAllItems1(string tableId)
        {
            var tableIdParameter = tableId != null ?
                new ObjectParameter("tableId", tableId) :
                new ObjectParameter("tableId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllItems1_Result>("GetAllItems1", tableIdParameter);
        }
    
        public virtual ObjectResult<SearchItem_Result1> SearchItem(string itemName, string tableId, Nullable<int> itemGroupId)
        {
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var tableIdParameter = tableId != null ?
                new ObjectParameter("tableId", tableId) :
                new ObjectParameter("tableId", typeof(string));
    
            var itemGroupIdParameter = itemGroupId.HasValue ?
                new ObjectParameter("itemGroupId", itemGroupId) :
                new ObjectParameter("itemGroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchItem_Result1>("SearchItem", itemNameParameter, tableIdParameter, itemGroupIdParameter);
        }
    
        public virtual ObjectResult<KOTCounterList_Result> KOTCounterList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KOTCounterList_Result>("KOTCounterList");
        }
    
        public virtual ObjectResult<FoodAreaList_Result> FoodAreaList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FoodAreaList_Result>("FoodAreaList");
        }
    
        public virtual ObjectResult<KOTCATList_Result> KOTCATList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KOTCATList_Result>("KOTCATList");
        }
    
        public virtual ObjectResult<SearchOccupiedTables_Result> SearchOccupiedTables(string term)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchOccupiedTables_Result>("SearchOccupiedTables", termParameter);
        }
    
        public virtual ObjectResult<SearchPaymentables_Result> SearchPaymentables(string term)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchPaymentables_Result>("SearchPaymentables", termParameter);
        }
    
        public virtual ObjectResult<SearchVacantTables_Result> SearchVacantTables(string term)
        {
            var termParameter = term != null ?
                new ObjectParameter("term", term) :
                new ObjectParameter("term", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SearchVacantTables_Result>("SearchVacantTables", termParameter);
        }
    
        public virtual ObjectResult<ItemMenuGroups_Result> ItemMenuGroups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ItemMenuGroups_Result>("ItemMenuGroups");
        }
    
        public virtual ObjectResult<AuthenticateUser_Result3> AuthenticateUser(string userName, string password)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AuthenticateUser_Result3>("AuthenticateUser", userNameParameter, passwordParameter);
        }
    }
}
